### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'BN_set_flags'

### ISSUE THREAD

**Issue by SeptiyanAndika** [nucypher/pyUmbral#135]
When i run test file. 
https://github.com/nucypher/mock-net/blob/master/umbral-demo.py
https://github.com/nucypher/mock-net/blob/master/test.py

got error 

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    config.set_default_curve()
  File "/Users/andika/Documents/Workspace/python/api-pyumbral/venv/lib/python3.6/site-packages/umbral/config.py", line 46, in set_default_curve
    return _CONFIG.set_curve(curve)
  File "/Users/andika/Documents/Workspace/python/api-pyumbral/venv/lib/python3.6/site-packages/umbral/config.py", line 42, in set_curve
    cls.__params = UmbralParameters(curve)
  File "/Users/andika/Documents/Workspace/python/api-pyumbral/venv/lib/python3.6/site-packages/umbral/params.py", line 16, in __init__
    self.order = openssl._get_ec_order_by_curve_nid(curve_nid)
  File "/Users/andika/Documents/Workspace/python/api-pyumbral/venv/lib/python3.6/site-packages/umbral/openssl.py", line 36, in _get_ec_order_by_curve_nid
    ec_order = _get_new_BN()
  File "/Users/andika/Documents/Workspace/python/api-pyumbral/venv/lib/python3.6/site-packages/umbral/openssl.py", line 17, in _get_new_BN
    backend._lib.BN_set_flags(new_bn, backend._lib.BN_FLG_CONSTTIME)
AttributeError: module 'lib' has no attribute 'BN_set_flags'

**Comment by tuxxy** [comment]
Hi, @SeptiyanAndika.

Unfortunately, we're waiting for an upstream release of cryptography.io that includes these changes. To resolve this, we had to compile wheels for cryptography.io for specific platforms. So far, we have x86_64 Linux builds for Python3.5 and Python3.6.

Do you mind saying what OS and Python version you're using is? Maybe we can guide you on building your own wheel, or even getting one built and added for the time being.

**Comment by SeptiyanAndika** [comment]
Hi, @tuxxy 
i use Python3.6. and use OS X 10.13.4

thanks

**Comment by tuxxy** [comment]
@SeptiyanAndika I have pushed up a wheel for Python3.5 and OS X.
Try doing `pipenv install` now and it should use the prebuilt wheel automatically.

Feel free to jump in our discord if other issues arise.

https://discord.gg/fWA5bKz

**Comment by SeptiyanAndika** [comment]
Thanks @tuxxy
