### ISSUE TITLE
AttributeError: 'int' object has no attribute '_EXPECTED_LENGTH'

### ISSUE THREAD

**Issue by w1397800** [nucypher/pyUmbral#174]
Running the code  'CapsuleFrag.from_bytes(cfrag.to_bytes())', i got a error which is 'AttributeError: 'int' object has no attribute '_EXPECTED_LENGTH' '
As you can see , i want to convert a 'cfrag'  to bytes and save it in a file so that i can use an external cfrag.

**Comment by tuxxy** [comment]
Hi, can you please post a full traceback and a working testcase, please?

**Comment by w1397800** [comment]
Traceback (most recent call last):
  File "/pythonProject/pyUmbral-Jun 2-2018/bytestring_splitter/__init__.py", line 91, in get_message_meta
    message_length = message_type[1]
TypeError: 'int' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pythonProject/pyUmbral-Jun 2-2018/test-wjh/test-1.py", line 29, in <module>
    Keys.gen_re_key(a_pri_b, b_pub_b, a_capsule_b, "wjh")
  File "/pythonProject/pyUmbral-Jun 2-2018/pre/Keys.py", line 102, in gen_re_key
    print(CapsuleFrag.from_bytes(cfrag.to_bytes()))
  File "/pythonProject/pyUmbral-Jun 2-2018/umbral/fragments.py", line 200, in from_bytes
    components = splitter(data, return_remainder=True)
  File "/pythonProject/pyUmbral-Jun 2-2018/bytestring_splitter/__init__.py", line 48, in __call__
    if len(self) > len(splittable):
  File "/pythonProject/pyUmbral-Jun 2-2018/bytestring_splitter/__init__.py", line 79, in __len__
    return sum(self.get_message_meta(m)[1] for m in self.message_types)
  File "/pythonProject/pyUmbral-Jun 2-2018/bytestring_splitter/__init__.py", line 79, in <genexpr>
    return sum(self.get_message_meta(m)[1] for m in self.message_types)
  File "/pythonProject/pyUmbral-Jun 2-2018/bytestring_splitter/__init__.py", line 94, in get_message_meta
    message_length = message_class._EXPECTED_LENGTH
AttributeError: 'int' object has no attribute '_EXPECTED_LENGTH'

**Comment by tuxxy** [comment]
Looks like an old version of `BytestringSplitter`. Try updating it.

**Comment by w1397800** [comment]
wonderful, it works! thanks for your help.  👍

**Comment by tuxxy** [comment]
No problem!
