### ISSUE TITLE
pytest crashes with ImportError on Python3.5

### ISSUE THREAD

**Issue by KPrasch** [nucypher/pyUmbral#208]
@cygnusv initially noticed this as a build failure on CircleCI: https://circleci.com/gh/nucypher/pyUmbral/1290

I have reproduced this locally with a fresh install; here is the traceback
```
$ pipenv run pytest
Traceback (most recent call last):
  File "/home/kieran/.local/share/virtualenvs/pyUmbral-rx3hYg0q/bin/pytest", line 7, in <module>
    from pytest import main
  File "/home/kieran/.local/share/virtualenvs/pyUmbral-rx3hYg0q/lib/python3.5/site-packages/pytest.py", line 9, in <module>
    from _pytest.config import main, UsageError, cmdline, hookspec, hookimpl
  File "/home/kieran/.local/share/virtualenvs/pyUmbral-rx3hYg0q/lib/python3.5/site-packages/_pytest/config/__init__.py", line 17, in <module>
    import _pytest._code
  File "/home/kieran/.local/share/virtualenvs/pyUmbral-rx3hYg0q/lib/python3.5/site-packages/_pytest/_code/__init__.py", line 3, in <module>
    from .code import Code  # noqa
  File "/home/kieran/.local/share/virtualenvs/pyUmbral-rx3hYg0q/lib/python3.5/site-packages/_pytest/_code/code.py", line 11, in <module>
    from _pytest.compat import _PY2, _PY3, PY35, safe_str
  File "/home/kieran/.local/share/virtualenvs/pyUmbral-rx3hYg0q/lib/python3.5/site-packages/_pytest/compat.py", line 46, in <module>
    from pathlib2 import Path
ImportError: No module named 'pathlib2'
```

**Comment by KPrasch** [comment]
`pipenv install --dev pytest` temporarily fixes the problem.

I noticed that `pytest` is not included in the output of `pipenv graph`, despite a successful installation (which includes `pytest` plugins!).  Manual installation cases `pathlib2` to be installed along with the other `pytest` dependencies:


```
$ pipenv install --dev pytest
Installing pytest...
Looking in indexes: https://pypi.python.org/simple
...
Installing collected packages: pathlib2
Successfully installed pathlib2-2.3.2
```

`pathlib2`  was probably just the first import the interpreter encountered when running `pytest`.

**Comment by cygnusv** [comment]
@KPrasch Can we close this?
