### ISSUE TITLE
Getting an error when "alices_private_key.to_bytes(password=password_bytes)"

### ISSUE THREAD

**Issue by seunghunjun** [nucypher/pyUmbral#225]
Quick question.
In windows-32 bit with umbral 0.1.1a3,
"alices_private_key.to_bytes()" seems work, but "alices_alices_private_key.to_bytes()" with an password option,  such as "private_key.to_bytes(password=password_with_bytes)", it gives an error like following
```
 Traceback (most recent call last):
  File "key_generator.py", line 56, in <module>
    gen_key()
  File "key_generator.py", line 26, in gen_key
    create_key_file("alices_private_key", alices_private_key.to_bytes(password=password_bytes))
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\umbral\keys.py", line 128, in to_bytes
    ).derive(password)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cryptography\hazmat\primitives\kdf\scrypt.py", line 60, in derive
    key_material, self._salt, self._length, self._n, self._r, self._p
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1950, in derive_scrypt
    self.openssl_assert(res == 1)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 105, in openssl_assert
    return binding._openssl_assert(self._lib, ok)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 76, in _openssl_assert
    errors_with_text
cryptography.exceptions.InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=101404844, lib=6, func=181, reason=172, reason_text=b'error:060B50AC:digital envelope routines:EVP_PBE_scrypt:memory limit exceeded')])
```
do you have any idea?

**Comment by michwill** [comment]
The quick idea is the following. Key derivation function uses scrypt, and scrypt is memory-hungry (by design, so that you cannot quickly brute force it). 32-bit Windows has severe memory limitations which could make scrypt running out of memory easily.

I'd summon @cygnusv here.

**Comment by KPrasch** [comment]
Related to https://github.com/nucypher/nucypher/issues/515

**Comment by cygnusv** [comment]
@michwill is exactly right, it's caused by the default memory needed by Scrypt [in pyumbral](https://github.com/nucypher/pyUmbral/blob/839106da3617314bb46fdb7fa77a0287920da0f0/umbral/keys.py#L103), which is approximately 1GB. You can reduce the amount of memory needed by changing the scrypt cost parameter, as follows:

`private_key.to_bytes(password=password_with_bytes, _scrypt_cost=15)`

A value of `_scrypt_cost=15` should require approximately 32 MB of memory. Note however that this value is orders of magnitude less secure than the default. See this [blog post](https://blog.filippo.io/the-scrypt-parameters/) for an explanation of Scrypt parameters.
