### ISSUE TITLE
Decrypts the re-encrypted ciphertext exception.

### ISSUE THREAD

**Issue by zhiyongvip** [nucypher/pyUmbral#239]
**Official demo：**

```
import random
from umbral import pre, keys, config, signing
config.set_default_curve()

alices_private_key = keys.UmbralPrivateKey.gen_key()
alices_public_key = alices_private_key.get_pubkey()

alices_signing_key = keys.UmbralPrivateKey.gen_key()
alices_verifying_key = alices_signing_key.get_pubkey()
alices_signer = signing.Signer(private_key=alices_signing_key)

plaintext = b'Proxy Re-encryption is cool!'
ciphertext, capsule = pre.encrypt(alices_public_key, plaintext)
cleartext = pre.decrypt(ciphertext=ciphertext,
                        capsule=capsule,
                        decrypting_key=alices_private_key)

bobs_private_key = keys.UmbralPrivateKey.gen_key()
bobs_public_key = bobs_private_key.get_pubkey()

kfrags = pre.generate_kfrags(delegating_privkey=alices_private_key,
                             signer=alices_signer,
                             receiving_pubkey=bobs_public_key,
                             threshold=10,
                             N=20)

bob_capsule = capsule

try:
    fail_decrypted_data = pre.decrypt(ciphertext=ciphertext,
                                      capsule=bob_capsule,
                                      decrypting_key=bobs_private_key)
except:
    print("Decryption failed! Bob doesn't has access granted yet.")


import random

kfrags = random.sample(kfrags,  # All kfrags from above
                       10)      # M - Threshold


bob_capsule.set_correctness_keys(delegating=alices_public_key,
                                 receiving=bobs_public_key,
                                 verifying=alices_verifying_key)
cfrags = list()  # Bob's cfrag collection
for kfrag in kfrags:
    cfrag = pre.reencrypt(kfrag=kfrag, capsule=bob_capsule)
    cfrags.append(cfrag)  # Bob collects a cfrag

for cfrag in cfrags:
    bob_capsule.attach_cfrag(cfrag)

#capsule serialization
with open("re-capsule.key", 'wb') as f:
    f.write(bob_capsule.to_bytes())
    f.close()

#capsule deserialization
re_capsule = ''
with open("re-capsule.key", 'rb') as f:
    re_capsule = f.read()
    f.close()

#bob_capsule = pre.Capsule.from_bytes(re_capsule, bobs_private_key.params)

bob_cleartext = pre.decrypt(ciphertext=ciphertext, capsule=bob_capsule, decrypting_key=bobs_private_key)
assert bob_cleartext == plaintext
```
**If add this line:**
```
#bob_capsule = pre.Capsule.from_bytes(re_capsule, bobs_private_key.params)
```

**Appear：**
```
Traceback (most recent call last):
  File "textencrypt.py", line 69, in <module>
    bob_cleartext = pre.decrypt(ciphertext=ciphertext, capsule=bob_capsule, decrypting_key=bobs_private_key)
  File "/Users/zero/dev/python/wencrypt/venv/lib/python3.7/site-packages/umbral/pre.py", line 492, in decrypt
    cleartext = dem.decrypt(ciphertext, authenticated_data=bytes(capsule))
  File "/Users/zero/dev/python/wencrypt/venv/lib/python3.7/site-packages/umbral/dem.py", line 57, in decrypt
    cleartext = self.cipher.decrypt(nonce, ciphertext, authenticated_data)
  File "/Users/zero/dev/python/wencrypt/venv/lib/python3.7/site-packages/cryptography/hazmat/primitives/ciphers/aead.py", line 55, in decrypt
    backend, self, nonce, data, associated_data, 16
  File "/Users/zero/dev/python/wencrypt/venv/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/aead.py", line 159, in _decrypt
    raise InvalidTag
cryptography.exceptions.InvalidTag
```

**If not add that line,that is work well!**

**Comment by zhiyongvip** [comment]
What did i do wrong?

**Comment by cygnusv** [comment]
hi @zhiyongvip, thanks for the comment!
The problem is that Capsules don't maintain the correctness keys and attached CFrags when serialized. This is a design decision in Umbral. Hence, if you try to decrypt a deserialized capsule without setting the correctness keys and Cfrags again, then it will fail as this Capsule can only be opened by Alice. It's exactly the same situation we show in the demo with the `try/except` code block.

The solution is very easy. Just set everything again after deserializing the capsule:
```
# Reading the capsule from disk:
bob_capsule = pre.Capsule.from_bytes(re_capsule, bobs_private_key.params)

# Setting the correctness keys:
bob_capsule.set_correctness_keys(delegating=alices_public_key,
                                 receiving=bobs_public_key,
                                 verifying=alices_verifying_key)

# Attaching the CFrags.
for cfrag in cfrags:
    bob_capsule.attach_cfrag(cfrag)

# Decrypting
bob_cleartext = pre.decrypt(ciphertext=ciphertext, capsule=bob_capsule, decrypting_key=bobs_private_key)
assert bob_cleartext == plaintext
```
